DECLARE EXTERNAL FUNCTION ASCII_REPLACE_CHARS
    VARCHAR(4096) CHARACTER SET ASCII NULL,
    VARCHAR(4096) CHARACTER SET ASCII NULL,
    VARCHAR(4096) CHARACTER SET ASCII NULL
    RETURNS VARCHAR(4096) CHARACTER SET ASCII FREE_IT
    ENTRY_POINT 'sbc_replace_chars' MODULE_NAME 'lua_udf';


DECLARE EXTERNAL FUNCTION BIN_TO_HEX
    VARCHAR(2048) CHARACTER SET OCTETS NULL
    RETURNS VARCHAR(4096) CHARACTER SET ASCII FREE_IT
    ENTRY_POINT 'bin_to_hex' MODULE_NAME 'lua_udf';


DECLARE EXTERNAL FUNCTION FILE_IS_READABLE
    VARCHAR(2048) CHARACTER SET OCTETS NULL
    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'file_is_readable' MODULE_NAME 'lua_udf';


DECLARE EXTERNAL FUNCTION LUA_UDF_RELOAD_LIBRARY

    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'reload_library' MODULE_NAME 'lua_udf';


DECLARE EXTERNAL FUNCTION MD5
    VARCHAR(4096) CHARACTER SET UTF8 NULL
    RETURNS VARCHAR(16) CHARACTER SET OCTETS FREE_IT
    ENTRY_POINT 'md5' MODULE_NAME 'lua_udf';


DECLARE EXTERNAL FUNCTION UTF8_MADE_OF
    VARCHAR(4096) CHARACTER SET UTF8,
    VARCHAR(4096) CHARACTER SET UTF8
    RETURNS DOUBLE PRECISION FREE_IT
    ENTRY_POINT 'utf8_made_of' MODULE_NAME 'lua_udf';


DECLARE EXTERNAL FUNCTION UTF8_REPLACE_BUT_CHARS
    VARCHAR(4096) CHARACTER SET UTF8,
    VARCHAR(4096) CHARACTER SET UTF8,
    VARCHAR(4096) CHARACTER SET UTF8
    RETURNS VARCHAR(4096) CHARACTER SET UTF8 FREE_IT
    ENTRY_POINT 'utf8_replace_but_chars' MODULE_NAME 'lua_udf';


DECLARE EXTERNAL FUNCTION UTF8_REPLACE_CHARS
    VARCHAR(4096) CHARACTER SET UTF8,
    VARCHAR(4096) CHARACTER SET UTF8,
    VARCHAR(4096) CHARACTER SET UTF8
    RETURNS VARCHAR(4096) CHARACTER SET UTF8 FREE_IT
    ENTRY_POINT 'utf8_replace_chars' MODULE_NAME 'lua_udf';


